### ISSUE TITLE
Play Button Missing Upon Hover

### ISSUE THREAD

**Issue by Nzzyme** [lethak/digitally_imported_userscript#71] opened 2023-08-20 07:39 UTC
**Steps to reproduce:**

1. Visit [radiotunes.com](https://www.radiotunes.com/)
2. You will observe that there are two sections:
- Today's Free Channels
- All Channels - Unlock with Premium

3. When you hover (not click) the mouse pointer over the channel tiles under the section "All Channels - Unlock with Premium", you will observe that the play icon is not displayed on any tile. When you hover the mouse pointer over the other section "Today's Free Channels", the play button is visible for all the station tiles.

![image](https://github.com/lethak/LTKDIFMU-userscript/assets/6959116/2be793f8-7fa7-446f-a794-7716e3b0c3a6)

4. Now, click on any genre under the section "All Channels - Unlock with Premium" as seen below:

![image](https://github.com/lethak/LTKDIFMU-userscript/assets/6959116/116aa3b6-a8dc-48a4-ae28-c0b7cf4aac29)

5. Now, again hover the mouse pointer over any of the station tiles under the section "All Channels - Unlock with Premium" and now you will observe that the play button appears correctly over all the station tiles as seen below:

![image](https://github.com/lethak/LTKDIFMU-userscript/assets/6959116/47f414d2-cb29-4031-8b18-24c1264ae578)

**Intended Functionality:**
After Steps 1 & 2, when we hover the mouse pointer over any station tile on the homepage, the play button should be visible and when the user clicks on the play button, the track from that station should play immediately at the bottom player without navigating to the station details page. Only when the user clicks on the station name (below the station tile), the page should redirect to the station details page.

**Comment by lethak** [comment] 2023-08-21 12:07
**Workaround**: navigate to another page using the menu and navigate back, it should update the UI accordingly

**Comment by lethak** [comment] 2023-08-21 12:10
same root cause as #66, closing

**Closed as completed by lethak** 2023-08-21 12:10 UTC
Labels: Has Workaround

**Comment by Nzzyme** [comment] 2023-08-22 06:21
> **Workaround**: navigate to another page using the menu and navigate back, it should update the UI accordingly

Yes, I am aware of the workaround but are you able to update the script so that the play button appears on all the tiles when the website is first opened?

As I mentioned, if I click on any genre, then the play button appears.

**Comment by lethak** [comment] 2023-08-24 15:52
This is a very complex issue related to how stuff is locked/unlocked and handled in the DOM rendering framework they use.
I see no quick win for now, so it will have to do until a solution present itself one day, eventually.
