### ISSUE TITLE
Tab/Session restoring problem (Vivaldi Browser)

### ISSUE THREAD

**Issue by esdeka** [lethak/digitally_imported_userscript#34] opened 2020-06-05 14:44 UTC
Not sure when this started, but sometimes I see the "disable your adblock page" and I have to confirm that I disabled my adblocker

First time this happened, I disabled ublock origin and reloaded. But once in a while it happens again , the only thing I can see that triggers the warning is this script.

After reloading the page a few times it's gone again, so just curious if you're aware if something was changed?

Vivaldi | 3.0.1874.38 (Stable channel) (64-bit)

EDIT:
# Workaround: 
Reload the page (F5)

**Comment by lethak** [comment] 2020-06-05 16:39
Hi

Assuming you are using the script in version 2020.3.429, It just has been working fine for a while. I mean with FF or Chrome. Never been using Vivaldi yet.

This kind of issue is often triggered by something different between how javascript & extensions are handled in browsers.

How are you loading the script in your browser ? using tempermonkey or similar ?
Can you provide a screenshot of the warning message ?
Do you have errors in the console ?

I have a new release candidate down the pipe, if you can provide me with more details maybe I can help to incorporate a patch before release.

Thanks.

**Comment by esdeka** [comment] 2020-06-07 04:25
Hey Lethak,

Long response ahead, got interested while testing.

Indeed Tampermonkey with 2020.3.429. And I realised I'm running pihole too so that's probably why I still see the adblock message with ublock disabled... I also have the Streamkeys extension for mediabuttons, but same problem if it's disabled. I think this started after I noticed Vivaldi was very outdated and updated it.

Thanks for the hint, I did some further testing, it seems the script doesn't load correctly after restarting the browser and the di.fm tab is loaded from the previous session (the remember tab feature). Console shows some errors about the script trying to read the channel property of undefined.

I tested Chrome and it also seems to have this problem, but no errors in the console. Firefox seems to handle it correctly. Also tested another userscript on a different site, which seems to have loaded fine after the session restore. I attached the Vivaldi and Chrome logs from after the restart.

Not sure if this is a browser/tampermonkey/userscript bug. I've made userscripts myself and wondered before how browsers restore sessions affect these type of scripts. But didn't learn much from google aside from browsers not following RFCs. 

So I guess it comes down to the script not loading/running correctly after Chrome/Vivaldi session restore, maybe you know why? Now I understand what causes it, so it's not important to fix but I'm more intrigued now

[chrome-www.di.fm-1591497976259.log](https://github.com/lethak/LTKDIFMU-userscript/files/4741391/chrome-www.di.fm-1591497976259.log)
[vivaldi-www.di.fm-1591497901454.log](https://github.com/lethak/LTKDIFMU-userscript/files/4741392/vivaldi-www.di.fm-1591497901454.log)

**Comment by lethak** [comment] 2020-06-08 04:44
Thanks for the logs and your input.
I'll run some test to try to reproduce.

So far it seems that those are the 2 main errors you are encountering:

* [DIUserscript :: AudioPlayer] FATAL ERROR while retrieving "listeningHistoryPast". err = Cannot read property 'id' of null
* [DIUserscript :: trackHistoryPlayButton] FATAL ERROR =  TypeError: Cannot read property 'channel' of undefined

In itself, they could have a wide variety of root causes and restoring tabs maybe a good clue.
I am confident I will be able to improve this use case when I have time to dive into it.

Can you confirm when you reload the tab everything is working as intended ?
Ideally could you tell me exactly what browser settings are you using on chrome and vivaldi in order to reproduce ?

Also, it may be important to use the same url you are using since this error can only happen on a channel's page. It is also possible this specific channel is having some weird track models I was not aware of and didn't handled properly.

**Comment by lethak** [comment] 2020-06-08 05:30
When restoring a chrome browser session, each tab is reloaded when focused for the first time, thus making everything work as intended. I really need a step by step guide from you in order to reproduce the problem.

**Comment by esdeka** [comment] 2020-06-08 07:03
Vivaldi seems to have different behaviour, the first focused tab is not completely reloaded. If the di.fm tab is not shown on startup and then clicked, it reloads fine.
For some reason Chrome doesn't do it anymore, unsure why.

To answer your questions:
- Indeed, after a reload everything works as expected
- I think I was testing the progressive channel in Vivaldi and the main di page in Chrome. The main page in Vivaldi also has no obvious errors when the load fails.

Reproduce steps if you want to try Vivaldi:
Vivaldi | 3.0.1874.38 W10
Tampermonkey 4.10
DIU 2020.3.429

1. Vivaldi settings: 
![image](https://user-images.githubusercontent.com/3588409/84000950-f4ad2380-a965-11ea-8316-8d87324e7ef7.png)
2. Go to https://www.di.fm/ and userscript will load fine
3. Close other tabs to make sure
3. Quit Vivaldi
4. Reopen Vivaldi
5. Page with di.fm will be loaded without userscript toast or buttons

Let me know if that works, otherwise I will do some further testing

**Comment by lethak** [comment] 2020-06-22 17:39
I have been investigating Vivaldi and I can reproduce the problem (no luck with chrome)

Its quite weird since the script do load, but somehow broken internally, thus resulting in some features not working as intended and the ad blocker message appearing.

Anyway, I think I found what was causing this weird behavior from within the script and revamped this specific portion of code, and it should be working just fine in the next release.

Thanks for the opportunity to try Vivaldi, I will be advising friends to give it a try too.

**Comment by lethak** [comment] 2020-06-22 19:24
Weird, this was fixed with my dev version, but not on live...

**Comment by lethak** [comment] 2021-04-09 18:52
Closing this issue since I cannot reproduce with latest version 2021.4.43 (build: 1579)

I think the situation was resolved with the same fixes from #48

**Closed as completed by lethak** 2021-04-09 18:52 UTC
Labels: bug, Has Workaround
